### ISSUE TITLE
Define the benchflow-benchmark.yml file

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/drivers-maker#16]
@simonedavico define the benchflow-benchmark.yml file and map related issues we already opened

**Comment by simonedavico** [comment]
What follows is the model of a BenchFlow benchmark configuration.

##### benchflow-benchmark #####

`benchflow-benchmark` includes:
-  `sut-name/suts-name`: the name of the sut, or a list of comma-separated names;
-  `suts-type`: type of suts (e.g, `WfMS`);
-  `benchmark-name`: defined by the client;
-  `description`: a description for the benchmark;
-  `drivers`: a list of `driver`s, where
    - `driver`: configuration for a driver, defined by a `type` and a list of `properties`;
- `properties`: configuration properties valid for the entire benchmark; contains parameters such as `trials` (the number of trials to be performed); most of this properties gets also mapped to Faban properties in the Faban configuration file (see #8)
- `sut-configuration`: defines a configuration for the sut, linking informations from client-defined services to BenchFlow services; this section is described in more detail below.

##### sut-configuration #####

`sut-configuration` is composed of two sections:

1. `deploy`: contains mappings `service -> server_alias`, where `server_alias` is an alias for a sever on which `service` is run;
2. `benchflow-config`: contains mappings `service -> (benchflow-service, [config])`, where:
    - `benchflow-service` is the name of a BenchFlow service to which `service` has to be bound; `config` is an optional list of properties which may be needed by `benchflow-service` to work correctly.

The interaction between `sut-configuration`, client-defined services specified in `docker-compose` and `benchflow-service`s is described more precisely in #17.

**Comment by simonedavico** [comment]
Updated file structure description to match the latest version.

**Comment by VincenzoFerme** [comment]
Some questions:

1. Why the  `target-service` contains also the `name` of the sut?
2. Is it possible to define all the following elements of a [Faban Driver](http://faban.org/1.3/docs/guide/driver/intro.html)?:
    - The System Under Test (SUT) comprises all components being tested and varies from benchmark to benchmark. The driver framework and the driver is usually not part of the SUT. Some non client-server benchmarks can however not differentiate between the SUT and the driver making the driver implicitly part of the SUT.
    - An Operation is a single unit of work executed by the user or the driver and timed, and managed by the driver.
    - An Operation Mix defines how operations are executed by a simulated user or driver thread.
    - An Operation Cycle defines the timing characteristics from one operation to the next.
    - A Metric is the resulting data of the operations collected over the steady state time of the benchmark operation.
    - Cycle Time defines the elapsed time between the begin of the previous operation to the begin of the current operation.
    - Think Time defines the elapsed time between the end of the previous operation to the begin of the current operation.
    - The Critical Section defines the portion of an operation in which the response time is measured.
    - Data Preparation Section defines the portion of an operation before the critical section where the data gets prepared.
    - Validation Section defines the portion of an operation after the critical section where the results get validated.
3. Do you handle the fact that only the first driver has to define the "Benchmark Definition", and this should enable all the configuration described on the following link: http://faban.org/1.0/docs/api/com/sun/faban/driver/BenchmarkDefinition.html?

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#190
