### ISSUE TITLE
Define the BENCHFLOW_ENV variables needed for the drivers-maker functionality

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/drivers-maker#19]
E.g., the endpoint of benchflow/compose

**Comment by simonedavico** [comment]
The ones needed now are:

- `BENCHFLOW_COMPOSE_ADDRESS`;
- `BENCHFLOW_MINIO_ACCESSKEY`;
- `BENCHFLOW_MINIO_SECREKEY`;

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#187
