### ISSUE TITLE
Rename everything to Test -> Experiment -> Trials

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/drivers-maker#48]
Some notes about renaming:

- `BenchFlowTest`
- ENV variables, in the deployment descriptors of BenchFlow services as well
- Minio bucket name
- `benchmarkName` field, e.g., in the experiments-manager as well
- `benchflow-benchmark.yml` file where it is used (e.g., drivers-maker, experiments-manager, ...)
- https://github.com/search?p=1&q=org%3Abenchflow+benchflowbenchmark&type=Code
- benchflow-client

The previous bull points came from the following search, please cross check it at the end of the changes: https://github.com/search?p=1&q=org%3Abenchflow+benchmark&ref=searchresults&type=Code&utf8=✓

**Comment by simonedavico** [comment]
This issue will be closed by [pull request #50](https://github.com/benchflow/drivers-maker/pull/50). 

This pull request addresses proper renaming in the `drivers-maker` component.
Similar issues will be opened in the repositories of the other components that need this refactoring (`experiments-manager`, `benchflow-client`).

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#152
