### ISSUE TITLE
Documents spoon dependencies resolution

### ISSUE THREAD

**Issue by simonedavico** [benchflow/drivers-maker#52]
This issue documents the way [spoon](http://spoon.gforge.inria.fr/) resolves the dependencies of the classes it processes, and how it impacts the design choices of the drivers-maker.

When spoon parses a class to process it, it needs to identify all the dependencies of the class; the only way we found to achieve this is to have the dependencies of the processed classes in the classpath of the jvm that starts spoon; in simpler words, this means that all dependencies for a processed class have to be in the classpath of the drivers-maker.

This also motivates why the classes used by the Faban benchmarks we generate (package `cloud.benchflow.driversmaker.generation`) are part of the drivers-maker source code.

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#173
