### ISSUE TITLE
Switch to mainstream version of monitors library in Dockerfile

### ISSUE THREAD

**Issue by simonedavico** [benchflow/drivers-maker#53]
As soon as the system is stable, we should switch to the mainstream (i.e., `benchflow`'s) release of the `monitors-drivers-library`. Right now, it is resolved to my fork's release (see [Dockerfile](https://github.com/simonedavico/faban-drivers-maker/blob/monitor-implementation/Dockerfile#L57)).

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#172
