### ISSUE TITLE
Switch to mainstream version of commons minio client

### ISSUE THREAD

**Issue by simonedavico** [benchflow/drivers-maker#54]
Currently the `drivers-maker` relies on the [v-dev release of my personal fork of benchflow-commons](https://github.com/simonedavico/commons/releases/v-dev) to retrieve the java minio client.

We should switch as soon as possible to the dependency from the release of the mainstream repository.

Related also to [this issue of experiments-manager](http://github.com/benchflow/experiments-manager/issues/41).

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#171
